// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_spawned_in_1000_levels = "CgkI7q_V8fMbEAIQDQ"; // <GPGSID>
        public const string achievement_level_40 = "CgkI7q_V8fMbEAIQCQ"; // <GPGSID>
        public const string achievement_level_30 = "CgkI7q_V8fMbEAIQCA"; // <GPGSID>
        public const string achievement_level_20 = "CgkI7q_V8fMbEAIQBQ"; // <GPGSID>
        public const string achievement_level_5 = "CgkI7q_V8fMbEAIQAg"; // <GPGSID>
        public const string achievement_level_25 = "CgkI7q_V8fMbEAIQBw"; // <GPGSID>
        public const string achievement_level_10 = "CgkI7q_V8fMbEAIQAw"; // <GPGSID>
        public const string achievement_spawned_in_500_levels = "CgkI7q_V8fMbEAIQCw"; // <GPGSID>
        public const string achievement_level_15 = "CgkI7q_V8fMbEAIQBA"; // <GPGSID>
        public const string achievement_welcome_to_hook_and_woosh = "CgkI7q_V8fMbEAIQDA"; // <GPGSID>
        public const string achievement_spawned_in_100_levels = "CgkI7q_V8fMbEAIQBg"; // <GPGSID>
        public const string achievement_level_50 = "CgkI7q_V8fMbEAIQCg"; // <GPGSID>
        public const string leaderboard_score = "CgkI7q_V8fMbEAIQAA"; // <GPGSID>

}

